#version 430 core

struct Pstruct{
  float picture[1920*1080*3];
  float factor;
};

layout(std430, binding = 0) buffer Result{
  float out_picture[];
};
layout(std430, binding = 1) buffer In_p1{
  Pstruct in_p1;
};
layout(local_size_x = 1000) in;

void main() {

    out_picture[gl_GlobalInvocationID.x] = out_picture[gl_GlobalInvocationID.x]  +
                                           in_p1.picture[gl_GlobalInvocationID.x] * in_p1.factor;

}
